const fs = require('fs');
const path = require('path');

// المجلدات المطلوب تأسيسها للموقع المتكامل
const directories = [
  'config',
  'models',
  'controllers',
  'routes',
  'public',
  'public/uploads' 
];

const files = {};

// 1. ملف التكوين السحابي لـ Vercel
files['vercel.json'] = [
  "{",
  "  \"version\": 2,",
  "  \"builds\": [",
  "    {",
  "      \"src\": \"server.js\",",
  "      \"use\": \"@vercel/node\"",
  "    }",
  "  ],",
  "  \"routes\": [",
  "    {",
  "      \"src\": \"/(.*)\",",
  "      \"dest\": \"server.js\"",
  "    }",
  "  ]",
  "}"
].join('\n');

// ملف package.json لإدارة المكتبات
files['package.json'] = `{
  "name": "al-najjar-showroom",
  "version": "1.0.0",
  "description": "الموقع الرسمي لمعرض النجار للأثاث الراقي",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "mongoose": "^8.2.0",
    "multer": "^1.4.5-lts.1"
  },
  "devDependencies": {
    "nodemon": "^3.1.0"
  }
}`;

files['.env'] = `PORT=5000
MONGODB_URI=mongodb://127.0.0.1:27017/al_najjar_db`;

// ملف الاتصال بقاعدة البيانات config/db.js المطور سحابياً لمنع التعليق
files['config/db.js'] = [
  "const mongoose = require('mongoose');",
  "",
  "let cachedConnection = null;",
  "",
  "const connectDB = async () => {",
  "  if (cachedConnection) {",
  "    console.log('Using cached database connection');",
  "    return cachedConnection;",
  "  }",
  "  try {",
  "    const conn = await mongoose.connect(process.env.MONGODB_URI, {",
  "      serverSelectionTimeoutMS: 5000,",
  "      socketTimeoutMS: 45000,",
  "    });",
  "    cachedConnection = conn;",
  "    console.log('Database connected successfully: ' + conn.connection.host);",
  "    return conn;",
  "  } catch (error) {",
  "    console.error('Database connection failed: ' + error.message);",
  "  }",
  "};",
  "",
  "module.exports = connectDB;"
].join('\n');

// نموذج المستخدم models/User.js
files['models/User.js'] = `const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  name: { type: String, required: [true, 'يرجى إدخال الاسم بالكامل'], trim: true },
  email: { type: String, required: [true, 'يرجى إدخال البريد الإلكتروني'], unique: true, lowercase: true, trim: true },
  password: { type: String, required: [true, 'يرجى إدخال كلمة المرور'] },
  phone: { type: String, required: [true, 'يرجى إدخال رقم الهاتف للتواصل'] },
  role: { type: String, enum: ['customer', 'admin', 'employee'], default: 'customer' }
}, { timestamps: true });

module.exports = mongoose.model('User', userSchema);`;

// نموذج المنتج models/Product.js
files['models/Product.js'] = `const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
  title: { type: String, required: [true, 'اسم المنتج مطلوب باللغة العربية'], trim: true },
  description: { type: String, required: [true, 'وصف المنتج مطلوب باللغة العربية'] },
  price: { type: Number, required: [true, 'سعر المنتج مطلوب بالجنيه المصري'] },
  discountPrice: { type: Number, default: 0 },
  images: [{ type: String, required: [true, 'يرجى إضافة صورة للمنتج'] }],
  category: { type: String, required: [true, 'يرجى اختيار القسم الرئيسي'] },
  woodType: { type: String, required: [true, 'يرجى تحديد نوع الخشب'] },
  dimensions: { type: String, trim: true },
  isAvailable: { type: Boolean, default: true },
  stock: { type: Number, default: 1 }
}, { timestamps: true });

module.exports = mongoose.model('Product', productSchema);`;

// نموذج طلبات التصنيع والعمولة models/CustomOrder.js
files['models/CustomOrder.js'] = `const mongoose = require('mongoose');

const customOrderSchema = new mongoose.Schema({
  customerName: { type: String, required: [true, 'يرجى إدخال اسم العميل'] },
  customerPhone: { type: String, required: [true, 'يرجى إدخال رقم الهاتف'] },
  title: { type: String, required: [true, 'يرجى كتابة نوع الأثاث المطلوب'] },
  details: { type: String, required: [true, 'يرجى كتابة تفاصيل ومقاسات طلبك'] },
  woodTypeRequested: { type: String, required: [true, 'يرجى تحديد نوع الخشب'] },
  estimatedBudget: { type: Number, default: 0 },
  
  costPrice: { type: Number, default: 0 },         
  sellingPrice: { type: Number, default: 0 },      
  amountPaid: { type: Number, default: 0 },        
  deliveryDate: { type: String, default: '' },     
  completionPercentage: { type: Number, default: 0 }, 
  
  status: { type: String, default: 'قيد المراجعة' }
}, { timestamps: true });

module.exports = mongoose.model('CustomOrder', customOrderSchema);`;

// وحدة التحكم والعمليات controllers/productController.js
files['controllers/productController.js'] = `const Product = require('../models/Product');
const CustomOrder = require('../models/CustomOrder');

exports.createProduct = async (req, res) => {
  try {
    const newProduct = new Product(req.body);
    const savedProduct = await newProduct.save();
    return res.status(201).json({ success: true, message: 'تم إضافة المنتج بنجاح إلى المعرض وتحديث القائمة', data: savedProduct });
  } catch (error) {
    return res.status(400).json({ success: false, message: error.message });
  }
};

exports.getProducts = async (req, res) => {
  try {
    const { category } = req.query;
    let queryFilter = {};
    if (category) queryFilter.category = category;
    const products = await Product.find(queryFilter).sort({ createdAt: -1 });
    return res.status(200).json({ success: true, data: products });
  } catch (error) {
    return res.status(500).json({ success: false, error: error.message });
  }
};

exports.createCustomOrder = async (req, res) => {
  try {
    const newOrder = new CustomOrder(req.body);
    const savedOrder = await newOrder.save();
    return res.status(201).json({ success: true, message: 'تم استلام طلب التصنيع بنجاح وجاري مراجعته', data: savedOrder });
  } catch (error) {
    return res.status(400).json({ success: false, message: error.message });
  }
};`;

// مسارات الروابط routes/productRoutes.js
files['routes/productRoutes.js'] = [
  "const express = require('express');",
  "const router = express.Router();",
  "const productController = require('../controllers/productController');",
  "",
  "router.post('/', productController.createProduct);",
  "router.get('/', productController.getProducts);",
  "router.post('/custom-order', productController.createCustomOrder);",
  "",
  "module.exports = router;"
].join('\n');

// واجهة مستخدم الويب الفاخرة لعملاء المعرض public/index.html
files['public/index.html'] = [
  "<!DOCTYPE html>",
  "<html lang=\"ar\" dir=\"rtl\" class=\"scroll-smooth\">",
  "<head>",
  "  <meta charset=\"UTF-8\">",
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
  "  <title>معرض النجار للأثاث الراقي</title>",
  "  <script src=\"https://cdn.tailwindcss.com\"></script>",
  "  <script>",
  "    tailwind.config = {",
  "      theme: {",
  "        extend: {",
  "          colors: {",
  "            luxuryGold: '#D4AF37',",
  "            luxuryDark: '#121212',",
  "            luxuryBeige: '#FDFBF7'",
  "          }",
  "        }",
  "      }",
  "    }",
  "  </script>",
  "  <!-- تضمين خط Tajawal الفاخر والأوضح هندسياً -->",
  "  <link href=\"https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;500;700;800;900&display=swap\" rel=\"stylesheet\">",
  "  <style>",
  "    body { font-family: 'Tajawal', sans-serif; background-color: #FAF9F6; -webkit-font-smoothing: antialiased; }",
  "    ",
  "    /* تأثير اللوجو المجسم الفاخر ثلاثي الأبعاد بتأثير ذهبي معدني لامع ومستمر */",
  "    @keyframes goldShimmer {",
  "      0% { background-position: 0% 50%; }",
  "      50% { background-position: 100% 50%; }",
  "      100% { background-position: 0% 50%; }",
  "    }",
  "    .text-3d-gold-shiny {",
  "      font-size: 1.8rem;",
  "      font-weight: 800;",
  "      background: linear-gradient(to right, #BF953F 0%, #FCF6BA 25%, #B38728 50%, #FBF5B7 75%, #AA771C 100%);",
  "      background-size: 200% auto;",
  "      animation: goldShimmer 4s linear infinite;",
  "      -webkit-background-clip: text;",
  "      -webkit-text-fill-color: transparent;",
  "      filter: drop-shadow(2px 2px 2px rgba(0, 0, 0, 0.6));",
  "      text-shadow: ",
  "        1px 1px 0px #8A6F27,",
  "        2px 2px 0px #70581E,",
  "        3px 3px 0px #574617;",
  "    }",
  "    @media (min-width: 768px) {",
  "      .text-3d-gold-shiny { font-size: 2.8rem; }",
  "    }",
  "  </style>",
  "</head>",
  "<body class=\"text-gray-800\">",
  "",
  "  <!-- شريط الإعلانات العلوي المقسم مع أرقام التواصل وأيقونات السوشيال ميديا الفخمة المدمجة -->",
  "  <div class=\"bg-luxuryGold text-black py-2.5 px-4 shadow-md border-b border-yellow-600/30\">",
  "    <div class=\"container mx-auto flex flex-col sm:flex-row justify-between items-center gap-2 text-center\">",
  "      <div class=\"text-sm font-bold tracking-wide\">",
  "        ✨ عرض خاص وحصري: خصم 25% وتوصيل مجاني لجميع الطلبات والمراكز بقنا لفترة محدودة! ✨",
  "      </div>",
  "      <!-- أرقام الهواتف بجانب أيقونات التواصل المذهبة الفاخرة المدمجة للتشغيل المباشر -->",
  "      <div class=\"flex items-center gap-3 text-xs font-bold\">",
  "        <span class=\"text-black/70 font-semibold\">اتصل بنا:</span>",
  "        <a href=\"tel:01060344580\" class=\"hover:underline transition-all duration-300\">01060344580</a>",
  "        <span class=\"text-black/30\">|</span>",
  "        <a href=\"tel:01003989727\" class=\"hover:underline transition-all duration-300\">01003989727</a>",
  "        <span class=\"text-black/30\">|</span>",
  "        <a href=\"https://www.facebook.com/bdallhalnjar.469115?locale=ar_AR\" target=\"_blank\" class=\"bg-black/10 hover:bg-black/20 p-1.5 rounded-full transition-all duration-300 hover:scale-110\" title=\"فيسبوك المعرض\">",
  "          <svg class=\"w-4 h-4 text-black\" fill=\"currentColor\" viewBox=\"0 0 24 24\">",
  "            <path d=\"M22 12c0-5.52-4.48-10-10-10S2 6.48 2 12c0 4.84 3.44 8.87 8 9.8V15H8v-3h2V9.5C10 7.57 11.57 6 13.5 6H16v3h-2c-.55 0-1 .45-1 1v2h3v3h-3v6.95c4.56-.93 8-4.96 8-9.75z\"/>",
  "          </svg>",
  "        </a>",
  "        <a href=\"https://wa.me/201060344580\" target=\"_blank\" class=\"bg-black/10 hover:bg-black/20 p-1.5 rounded-full transition-all duration-300 hover:scale-110\" title=\"واتساب المعرض\">",
  "          <svg class=\"w-4 h-4 text-black\" fill=\"currentColor\" viewBox=\"0 0 24 24\">",
  "            <path d=\"M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.05-.149-.669-1.612-.916-2.207-.242-.596-.487-.514-.67-.515-.173-.002-.371-.002-.57-.002-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L0 24l6.135-1.61a11.75 11.75 0 005.908 1.597h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413\"/>",
  "          </svg>",
  "        </a>",
  "      </div>",
  "    </div>",
  "  </div>",
  "",
  "  <!-- هيدر الموقع الفاخر مع اللوجو المجسم الكبير -->",
  "  <header class=\"bg-luxuryDark text-white sticky top-0 z-50 border-b border-yellow-600/20 shadow-lg\">",
  "    <div class=\"container mx-auto px-4 py-4 flex flex-col md:flex-row justify-between items-center gap-4\">",
  "      <div class=\"text-center md:text-right\">",
  "        <h1 class=\"text-3d-gold-shiny\">معرض النجار للأثاث الراقي</h1>",
  "        <p class=\"text-xs text-gray-400 mt-1\">راحة بيتك تبدأ من عندنا</p>",
  "      </div>",
  "      <nav class=\"flex gap-6 text-sm font-medium items-center\">",
  "        <a href=\"#products\" class=\"hover:text-luxuryGold transition-all duration-300\">معرض المنتجات</a>",
  "        <a href=\"#custom\" class=\"hover:text-luxuryGold transition-all duration-300\">طلب تصنيع عمولة</a>",
  "        <a href=\"#contact\" class=\"hover:text-luxuryGold transition-all duration-300\">تواصل معنا</a>",
  "        <button onclick=\"openAdminLogin()\" class=\"bg-luxuryGold/10 text-luxuryGold border border-luxuryGold/30 px-4 py-1.5 rounded hover:bg-luxuryGold hover:text-black transition-all duration-300 text-xs font-bold\">لوحة التحكم</button>",
  "      </nav>",
  "    </div>",
  "  </header>",
  "",
  "  <!-- نافذة تسجيل دخول المدير والموظفين -->",
  "  <div id=\"admin-login-modal\" class=\"fixed inset-0 bg-black/80 z-50 hidden flex justify-center items-center p-4\">",
  "    <div class=\"bg-[#1C1C1C] text-white p-8 rounded-lg max-w-md w-full border border-luxuryGold/30 relative\">",
  "      <button onclick=\"closeAdminLogin()\" class=\"absolute top-4 left-4 text-gray-400 hover:text-white text-xl\">&times;</button>",
  "      <h4 class=\"text-xl font-bold text-luxuryGold text-center mb-6\">بوابة تسجيل الدخول للإدارة والموظفين</h4>",
  "      <div class=\"space-y-4\">",
  "        <div>",
  "          <label class=\"block text-xs text-gray-400 mb-2\">البريد الإلكتروني (Username)</label>",
  "          <input type=\"email\" id=\"adminEmailInput\" placeholder=\"example@najjar.com\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold text-center text-sm\">",
  "        </div>",
  "        <div>",
  "          <label class=\"block text-xs text-gray-400 mb-2\">كلمة المرور (Password)</label>",
  "          <input type=\"password\" id=\"adminPasswordInput\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold text-center tracking-widest\">",
  "        </div>",
  "        <button onclick=\"verifyAdmin()\" class=\"w-full bg-luxuryGold text-black font-bold py-3 rounded hover:bg-yellow-500 transition-all duration-300\">تسجيل الدخول</button>",
  "      </div>",
  "    </div>",
  "  </div>",
  "",
  "  <!-- لوحة تحكم الإدارة الكاملة المحدثة (Admin Control Center) -->",
  "  <section id=\"admin-panel\" class=\"bg-luxuryGold/5 border-b border-luxuryGold/20 py-8 px-4 hidden\">",
  "    <div class=\"container mx-auto max-w-6xl bg-[#121212] text-white p-8 rounded-lg border border-luxuryGold/20 space-y-12\">",
  "      <div class=\"flex justify-between items-center border-b border-white/10 pb-4\">",
  "        <div class=\"text-right\">",
  "          <h4 class=\"text-2xl font-bold text-luxuryGold\">لوحة إدارة وتحكم معرض النجار</h4>",
  "          <p class=\"text-xs text-gray-400 mt-1\">مرحباً بك مجدداً: <span id=\"logged-admin-name\" class=\"text-luxuryGold font-bold\"></span></p>",
  "        </div>",
  "        <button onclick=\"logoutAdmin()\" class=\"bg-red-600/20 text-red-500 border border-red-600/40 px-4 py-1 rounded text-xs hover:bg-red-600 hover:text-white transition-all duration-300\">إغلاق اللوحة</button>",
  "      </div>",
  "",
  "      <!-- التبويبات الداخلية للوحة التحكم بعد إضافة ميزة حظر المستخدمين للموظف العادي -->",
  "      <div class=\"flex border-b border-white/10 gap-4 pb-3 text-sm\">",
  "        <button onclick=\"switchAdminTab('tab-product')\" class=\"text-luxuryGold font-bold px-4 py-1 border-b-2 border-luxuryGold\" id=\"btn-tab-product\">إضافة منتجات وصور</button>",
  "        <button onclick=\"switchAdminTab('tab-orders')\" class=\"text-gray-400 px-4 py-1 hover:text-white\" id=\"btn-tab-orders\">متابعة حسابات العمولة والورشة</button>",
  "        <button onclick=\"switchAdminTab('tab-fb-writer')\" class=\"text-gray-400 px-4 py-1 hover:text-white\" id=\"btn-tab-fb-writer\">✍️ مولّد بوستات فيسبوك</button>",
  "        <button onclick=\"switchAdminTab('tab-users')\" class=\"text-gray-400 px-4 py-1 hover:text-white hidden\" id=\"btn-tab-users\">إضافة حسابات وصلاحيات</button>",
  "      </div>",
  "",
  "      <!-- تبويب 1: إضافة منتج مع رفع صور ومقاطع فيديو محلية وقائمة حذف المنتجات المعروضة -->",
  "      <div id=\"tab-product\" class=\"space-y-6\">",
  "        <h5 class=\"text-lg font-bold text-gray-200\">نشر قطعة أثاث جديدة في المعرض</h5>",
  "        <form id=\"add-product-form\" onsubmit=\"addNewProduct(event)\" class=\"space-y-4 text-right\">",
  "          <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">اسم القطعة بالأثاث</label>",
  "              <input type=\"text\" id=\"prodTitle\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "            </div>",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">القسم الرئيسي</label>",
  "              <select id=\"prodCategory\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2.5 text-white focus:outline-none focus:border-luxuryGold\">",
  "                <option value=\"غرف نوم\">غرف نوم</option>",
  "                <option value=\"غرف أطفال\">غرف أطفال</option>",
  "                <option value=\"انتريه\">انتريه</option>",
  "                <option value=\"ركنيات\">ركنيات</option>",
  "                <option value=\"سفرة\">سفرة</option>",
  "                <option value=\"مطابخ\">مطابخ</option>",
  "              </select>",
  "            </div>",
  "          </div>",
  "          <div class=\"grid grid-cols-1 md:grid-cols-3 gap-4\">",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">السعر الأصلي (بالجنيه المصري)</label>",
  "              <input type=\"number\" id=\"prodPrice\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "            </div>",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">سعر الخصم إن وجد (0 في حال عدم وجود خصم)</label>",
  "              <input type=\"number\" id=\"prodDiscount\" value=\"0\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">نوع الخشب المستخدم (مثال: زان أحمر فرنسي)</label>",
  "            <input type=\"text\" id=\"prodWood\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">أبعاد القطعة ومقاساتها (مثال: سرير 180سم - دولاب 280سم)</label>",
  "            <input type=\"text\" id=\"prodDimensions\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">رفع صورة أو فيديو القطعة من جهازك المحلي</label>",
  "            <input type=\"file\" id=\"prodFile\" onchange=\"handleLocalUpload(event)\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-1.5 text-white focus:outline-none focus:border-luxuryGold\">",
  "            <input type=\"hidden\" id=\"prodImage\" value=\"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=600\">",
  "          </div>",
  "        </div>",
  "        <div>",
  "          <label class=\"block text-xs text-gray-400 mb-2\">وصف المنتج وتفاصيل التصميم والتشطيب</label>",
  "          <textarea id=\"prodDescription\" rows=\"3\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\"></textarea>",
  "        </div>",
  "        <div class=\"text-center pt-2\">",
  "          <button type=\"submit\" class=\"bg-luxuryGold text-black px-12 py-3 rounded font-bold hover:bg-yellow-500 transition-all duration-300 shadow-lg text-sm\">حفظ ونشر القطعة بالمعرض</button>",
  "        </div>",
  "      </form>",
  "      ",
  "      <!-- جدول حذف وإلغاء قطع المعرض الحالية -->",
  "      <div class=\"border-t border-white/10 pt-6 mt-8 space-y-4\">",
  "        <h6 class=\"text-md font-bold text-gray-300\">قائمة الأثاث المعروض حالياً في الموقع (للحذف والتعديل)</h6>",
  "        <div class=\"overflow-x-auto\">",
  "          <table class=\"w-full text-right text-xs border-collapse border border-white/5\">",
  "            <thead>",
  "              <tr class=\"bg-white/5 text-gray-300\">",
  "                <th class=\"p-2.5 border border-white/5\">اسم القطعة</th>",
  "                <th class=\"p-2.5 border border-white/5\">القسم</th>",
  "                <th class=\"p-2.5 border border-white/5\">السعر</th>",
  "                <th class=\"p-2.5 border border-white/5\">إجراءات الحذف</th>",
  "              </tr>",
  "            </thead>",
  "            <tbody id=\"manage-products-tbody\">",
  "              <!-- تعبأ ديناميكياً -->",
  "            </tbody>",
  "          </table>",
  "        </div>",
  "      </div>",
  "      </div>",
  "",
  "      <!-- تبويب 2: متابعة حسابات ومقايسات العمولة والورشة -->",
  "      <div id=\"tab-orders\" class=\"space-y-6 hidden\">",
  "        <div class=\"flex flex-col md:flex-row justify-between items-center gap-4\">",
  "          <h5 class=\"text-lg font-bold text-gray-200\">إدارة طلبات تفصيل العمولة ومتابعة المستحقات المالية</h5>",
  "          <div class=\"flex gap-3\">",
  "            <button onclick=\"exportToExcel()\" class=\"bg-yellow-600 text-black px-4 py-2 rounded text-xs font-bold hover:bg-yellow-500 transition-all duration-300 flex items-center gap-1\">📥 تحميل كشيت إكسيل</button>",
  "            <button onclick=\"openManualOrderModal()\" class=\"bg-green-600 text-white px-4 py-2 rounded text-xs font-bold hover:bg-green-500 transition-all duration-300\">➕ إضافة طلب عمولة يدوي</button>",
  "          </div>",
  "        </div>",
  "        <div class=\"overflow-x-auto\">",
  "          <table class=\"w-full text-right text-sm border-collapse border border-white/10\">",
  "            <thead>",
  "              <tr class=\"bg-luxuryGold/10 text-luxuryGold\">",
  "                <th class=\"p-3 border border-white/10\">العميل وهاتفه</th>",
  "                <th class=\"p-3 border border-white/10\">الطلب المقدر</th>",
  "                <th class=\"p-3 border border-white/10\">التكلفة/الجملة</th>",
  "                <th class=\"p-3 border border-white/10\">سعر البيع</th>",
  "                <th class=\"p-3 border border-white/10\">المدفوع</th>",
  "                <th class=\"p-3 border border-white/10\">المتبقي</th>",
  "                <th class=\"p-3 border border-white/10\">تاريخ التسليم</th>",
  "                <th class=\"p-3 border border-white/10\">نسبة الإنجاز</th>",
  "                <th class=\"p-3 border border-white/10\">إجراءات المتابعة</th>",
  "              </tr>",
  "            </thead>",
  "            <tbody id=\"orders-table-body\">",
  "            </tbody>",
  "          </table>",
  "        </div>",
  "      </div>",
  "",
  "      <!-- تبويب 3: مولد بوستات فيسبوك الترويجي الذكي للمبيعات -->",
  "      <div id=\"tab-fb-writer\" class=\"space-y-6 hidden text-right\">",
  "        <h5 class=\"text-lg font-bold text-gray-200\">✍️ كاتب المحتوى التسويقي لفيسبوك بنقرة واحدة</h5>",
  "        <p class=\"text-xs text-gray-400\">قم بإنشاء نص ترويجي جذاب جاهز للنسخ والنشر لمنتجات المعرض لزيادة التفاعل والمبيعات.</p>",
  "        <div class=\"space-y-4 max-w-2xl\">",
  "          <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">اسم المنتج (مثال: صالون قصر النبلاء مذهب)</label>",
  "              <input type=\"text\" id=\"fbProdName\" required placeholder=\"اكتب اسم المنتج للتسويق\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2.5 text-white focus:outline-none focus:border-luxuryGold\">",
  "            </div>",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">العرض الترويجي المرفق</label>",
  "              <select id=\"fbPromoType\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold\">",
  "                <option value=\"خصم خاص 25% وتوصيل مجاني لفترة محدودة\">خصم خاص 25% وتوصيل مجاني لقنا والمحافظات المجاورة</option>",
  "                <option value=\"عرض العروسين المتكامل (شقة كاملة بسعر خاص)\">عرض العروسين المتكامل (شقة كاملة بسعر مميز)</option>",
  "                <option value=\"تصنيع وتفصيل مخصوص عمولة بأرقى الأخشاب الطبيعية\">تصنيع وتفصيل مخصوص عمولة بأرقى الأخشاب والورش الخاصة بنا</option>",
  "              </select>",
  "            </div>",
  "          </div>",
  "          <button onclick=\"generateFacebookPost()\" class=\"bg-luxuryGold text-black font-bold px-8 py-3 rounded hover:bg-yellow-500 transition-all duration-300 text-sm\">✨ توليد بوست فيسبوك جذاب</button>",
  "          ",
  "          <div class=\"hidden\" id=\"generated-post-container\">",
  "            <label class=\"block text-xs text-gray-400 mb-2\">البوست التسويقي الجاهز للنشر (انسخ والصق على فيسبوك):</label>",
  "            <textarea id=\"fbPostOutput\" rows=\"10\" class=\"w-full bg-black/60 border border-luxuryGold/30 rounded p-4 text-white focus:outline-none text-sm leading-relaxed\"></textarea>",
  "            <button onclick=\"copyFbPost()\" class=\"mt-3 bg-green-600 text-white font-bold px-6 py-2 rounded hover:bg-green-500 transition text-xs\">📋 نسخ نص المنشور</button>",
  "          </div>",
  "        </div>",
  "      </div>",
  "",
  "      <!-- تبويب 4: إدارة الحسابات وإضافة الموظفين والمدراء الجدد وحذفهم (Admin Only) -->",
  "      <div id=\"tab-users\" class=\"space-y-6 hidden\">",
  "        <h5 class=\"text-lg font-bold text-gray-200\">تسجيل حساب جديد وتحديد الصلاحيات للموظفين أو المدراء</h5>",
  "        <form id=\"add-user-form\" onsubmit=\"addNewUser(event)\" class=\"space-y-4 text-right\">",
  "          <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">الاسم بالكامل</label>",
  "              <input type=\"text\" id=\"userFullName\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "            </div>",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">البريد الإلكتروني (لتسجيل الدخول)</label>",
  "              <input type=\"email\" id=\"userEmail\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "            </div>",
  "          </div>",
  "          <div class=\"grid grid-cols-1 md:grid-cols-3 gap-4\">",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">كلمة المرور</label>",
  "              <input type=\"password\" id=\"userPass\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "            </div>",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">رقم الهاتف للتواصل</label>",
  "              <input type=\"tel\" id=\"userPhone\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "            </div>",
  "            <div>",
  "              <label class=\"block text-xs text-gray-400 mb-2\">نوع الحساب / الصلاحية</label>",
  "              <select id=\"userRole\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2.5 text-white focus:outline-none focus:border-luxuryGold\">",
  "                <option value=\"employee\">موظف مبيعات / متابعة</option>",
  "                <option value=\"admin\">مدير مالي وإداري (Admin)</option>",
  "              </select>",
  "            </div>",
  "          </div>",
  "          <div class=\"text-center pt-2\">",
  "            <button type=\"submit\" class=\"bg-luxuryGold text-black px-12 py-3 rounded font-bold hover:bg-yellow-500 transition-all duration-300 shadow-lg text-sm\">تسجيل وتفعيل الحساب</button>",
  "          </div>",
  "        </form>",
  "        ",
  "        <!-- جدول استعراض وحذف الموظفين والمدراء الحاليين -->",
  "        <div class=\"border-t border-white/10 pt-6 mt-8 space-y-4\">",
  "          <h6 class=\"text-md font-bold text-gray-300\">حسابات الموظفين والمدراء الحاليين (لتعديل وإلغاء الصلاحيات)</h6>",
  "          <div class=\"overflow-x-auto\">",
  "            <table class=\"w-full text-right text-xs border-collapse border border-white/5\">",
  "              <thead>",
  "                <tr class=\"bg-white/5 text-gray-300\">",
  "                  <th class=\"p-2.5 border border-white/5\">الاسم</th>",
  "                  <th class=\"p-2.5 border border-white/5\">البريد الإلكتروني</th>",
  "                  <th class=\"p-2.5 border border-white/5\">الصلاحية</th>",
  "                  <th class=\"p-2.5 border border-white/5\">إجراءات إلغاء الصلاحية</th>",
  "                </tr>",
  "              </thead>",
  "              <tbody id=\"manage-users-tbody\">",
  "                <!-- تعبأ ديناميكياً -->",
  "              </tbody>",
  "            </table>",
  "          </div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  </section>",
  "",
  "  <!-- نافذة تحديث تفاصيل طلب العمولة -->",
  "  <div id=\"order-update-modal\" class=\"fixed inset-0 bg-black/90 z-50 hidden flex justify-center items-center p-4\">",
  "    <div class=\"bg-[#1C1C1C] text-white p-8 rounded-lg max-w-lg w-full border border-luxuryGold/30 relative\">",
  "      <button onclick=\"closeOrderUpdateModal()\" class=\"absolute top-4 left-4 text-gray-400 hover:text-white text-xl\">&times;</button>",
  "      <h4 class=\"text-xl font-bold text-luxuryGold text-center mb-6\">تحديث تفاصيل تصنيع العمولة والحساب المالي</h4>",
  "      <input type=\"hidden\" id=\"updateOrderId\">",
  "      <div class=\"space-y-4 text-right\">",
  "        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">سعر التكلفة / الجملة (ج.م)</label>",
  "            <input type=\"number\" id=\"updateCost\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">سعر البيع للعميل (ج.م)</label>",
  "            <input type=\"number\" id=\"updateSelling\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">المبلغ المدفوع (العربون) (ج.م)</label>",
  "            <input type=\"number\" id=\"updatePaid\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">موعد التسليم المتوقع</label>",
  "            <input type=\"text\" id=\"updateDelivery\" placeholder=\"مثال: 2024/11/01\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div>",
  "          <label class=\"block text-xs text-gray-400 mb-2\">نسبة الإنجاز والتنفيذ في الورشة</label>",
  "          <select id=\"updateCompletion\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "            <option value=\"0\">0% - قيد الانتظار</option>",
  "            <option value=\"10\">10% - تصميم وتخطيط</option>",
  "            <option value=\"25\">25% - تقطيع وتأسيس الخشب</option>",
  "            <option value=\"50\">50% - التجميع الأولي الهيكل</option>",
  "            <option value=\"75\">75% - مرحلة القشرة والتشطيب</option>",
  "            <option value=\"100\">100% - جاهز للتسليم النهائي</option>",
  "          </select>",
  "        </div>",
  "        <div class=\"flex gap-4 pt-2\">",
  "          <button onclick=\"saveOrderUpdate()\" class=\"w-2/3 bg-luxuryGold text-black font-bold py-3 rounded hover:bg-yellow-500 transition-all duration-300\">حفظ وتعديل التغييرات</button>",
  "          <button onclick=\"deleteOrder()\" class=\"w-1/3 bg-red-600/20 text-red-500 border border-red-600/40 font-bold py-3 rounded hover:bg-red-600 hover:text-white transition-all duration-300\">حذف الطلب</button>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  </div>",
  "",
  "  <!-- نافذة إضافة طلب عمولة يدوي جديد من الإدمن (Manual Order Modal) -->",
  "  <div id=\"manual-order-modal\" class=\"fixed inset-0 bg-black/95 z-50 hidden flex justify-center items-center p-4\">",
  "    <div class=\"bg-[#1C1C1C] text-white p-8 rounded-lg max-w-2xl w-full border border-luxuryGold/30 relative max-h-[90vh] overflow-y-auto\">",
  "      <button onclick=\"closeManualOrderModal()\" class=\"absolute top-4 left-4 text-gray-400 hover:text-white text-xl\">&times;</button>",
  "      <h4 class=\"text-xl font-bold text-luxuryGold text-center mb-6\">تسجيل وإضافة طلب عمولة يدوي جديد</h4>",
  "      <form id=\"manual-order-form\" onsubmit=\"submitManualOrder(event)\" class=\"space-y-4 text-right\">",
  "        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
  "          <div>",
  "            <label class=\"block text-sm font-medium mb-2 text-gray-300\">اسم العميل</label>",
  "            <input type=\"text\" id=\"mCustName\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-sm font-medium mb-2 text-gray-300\">رقم هاتف العميل</label>",
  "            <input type=\"tel\" id=\"mCustPhone\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div class=\"grid grid-cols-1 md:grid-cols-3 gap-4\">",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">نوع الأثاث المطلوب</label>",
  "            <input type=\"text\" id=\"mTitle\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">نوع الخشب المتفق عليه</label>",
  "            <input type=\"text\" id=\"mWood\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">تاريخ التسليم المتوقع</label>",
  "            <input type=\"text\" id=\"mDelivery\" placeholder=\"مثال: 2024/11/01\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div class=\"grid grid-cols-1 md:grid-cols-3 gap-4\">",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">تكلفة الجملة / التكلفة (ج.م)</label>",
  "            <input type=\"number\" id=\"mCostPrice\" value=\"0\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">سعر البيع المتفق عليه (ج.م)</label>",
  "            <input type=\"number\" id=\"mSellingPrice\" value=\"0\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-xs text-gray-400 mb-2\">المقدم / العربون المدفوع (ج.م)</label>",
  "            <input type=\"number\" id=\"mAmountPaid\" value=\"0\" class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div>",
  "          <label class=\"block text-xs text-gray-400 mb-2\">تفاصيل الطلب، الألوان، والمقاسات بالكامل</label>",
  "          <textarea id=\"mDetails\" rows=\"3\" required class=\"w-full bg-black/40 border border-white/10 rounded px-4 py-2 text-white focus:outline-none focus:border-luxuryGold\"></textarea>",
  "        </div>",
  "        <button type=\"submit\" class=\"w-full bg-green-600 text-white font-bold py-3 rounded hover:bg-green-500 transition-all duration-300\">حفظ وإدراج الطلب مباشرة بقائمة العمولة</button>",
  "      </form>",
  "    </div>",
  "  </div>",
  "",
  "  <!-- خلفية ترحيبية وتذكرة الخصم (Hero Section) -->",
  "  <section class=\"relative bg-luxuryDark text-white py-24 px-4 text-center overflow-hidden border-b border-luxuryGold/20\">",
  "    <div class=\"absolute inset-0 opacity-20 bg-[url('https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200')] bg-cover bg-center\"></div>",
  "    <div class=\"relative container mx-auto max-w-3xl\">",
  "      <span class=\"inline-block px-4 py-1 bg-luxuryGold/10 border border-luxuryGold/30 rounded-full text-luxuryGold text-sm mb-4\">أفخم الموديلات بأسعار مميزة</span>",
  "      <h2 class=\"text-4xl md:text-5xl font-extrabold mb-6 leading-tight\">بيت فخم، مريح، وتفاصيل تنبض بالجمال</h2>",
  "      <p class=\"text-gray-300 mb-8 leading-relaxed text-lg\">نصنع لك أرقى غرف النوم، غرف الأطفال، الركنيات، والمطابخ بأيدي أمهر الخبراء ومن أجود أنواع الخشب الطبيعي لتناسب ذوقك الرفيع.</p>",
  "      <div class=\"flex justify-center gap-4\">",
  "        <a href=\"#products\" class=\"bg-luxuryGold text-black px-8 py-3 rounded-md font-bold hover:bg-yellow-500 transition-all duration-300 shadow-lg\">تصفح المعرض</a>",
  "        <a href=\"#custom\" class=\"border border-white/40 px-8 py-3 rounded-md font-bold hover:bg-white/10 transition-all duration-300\">طلب تصنيع خاص</a>",
  "      </div>",
  "    </div>",
  "  </section>",
  "",
  "  <!-- المنتجات والمعرض الديناميكي -->",
  "  <main class=\"container mx-auto px-4 py-16\" id=\"products\">",
  "    <div class=\"text-center mb-12\">",
  "      <h3 class=\"text-3xl font-bold text-luxuryDark\">تشكيلتنا الراقية</h3>",
  "      <div class=\"w-24 h-1 bg-luxuryGold mx-auto mt-3\"></div>",
  "    </div>",
  "",
  "    <!-- تصفية حسب الأقسام (تم إضافة قسم غرف أطفال هنا) -->",
  "    <div class=\"flex flex-wrap justify-center gap-3 mb-12\" id=\"categories-tabs\">",
  "      <button onclick=\"loadProducts('')\" class=\"px-6 py-2 bg-luxuryDark text-white rounded-full text-sm font-semibold hover:bg-luxuryGold hover:text-black transition-all duration-300\">الكل</button>",
  "      <button onclick=\"loadProducts('غرف نوم')\" class=\"px-6 py-2 bg-white border border-gray-200 rounded-full text-sm font-semibold hover:bg-luxuryGold hover:text-black transition-all duration-300\">غرف نوم</button>",
  "      <button onclick=\"loadProducts('غرف أطفال')\" class=\"px-6 py-2 bg-white border border-gray-200 rounded-full text-sm font-semibold hover:bg-luxuryGold hover:text-black transition-all duration-300\">غرف أطفال</button>",
  "      <button onclick=\"loadProducts('انتريه')\" class=\"px-6 py-2 bg-white border border-gray-200 rounded-full text-sm font-semibold hover:bg-luxuryGold hover:text-black transition-all duration-300\">انتريه</button>",
  "      <button onclick=\"loadProducts('ركنيات')\" class=\"px-6 py-2 bg-white border border-gray-200 rounded-full text-sm font-semibold hover:bg-luxuryGold hover:text-black transition-all duration-300\">ركنيات</button>",
  "      <button onclick=\"loadProducts('سفرة')\" class=\"px-6 py-2 bg-white border border-gray-200 rounded-full text-sm font-semibold hover:bg-luxuryGold hover:text-black transition-all duration-300\">سفرة</button>",
  "      <button onclick=\"loadProducts('مطابخ')\" class=\"px-6 py-2 bg-white border border-gray-200 rounded-full text-sm font-semibold hover:bg-luxuryGold hover:text-black transition-all duration-300\">مطابخ</button>",
  "    </div>",
  "",
  "    <!-- شبكة المنتجات -->",
  "    <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8\" id=\"products-grid\">",
  "      <!-- المنتجات تظهر هنا ديناميكياً -->",
  "    </div>",
  "  </main>",
  "",
  "  <!-- قسم التصنيع المخصص (عمولة) -->",
  "  <section class=\"bg-luxuryDark text-white py-20 px-4 border-t border-luxuryGold/20\" id=\"custom\">",
  "    <div class=\"container mx-auto max-w-4xl\">",
  "      <div class=\"text-center mb-12\">",
  "        <span class=\"text-luxuryGold font-semibold text-sm\">خدمة التصنيع المخصص حسب الطلب (عمولة)</span>",
  "        <h3 class=\"text-3xl font-bold mt-2\">اصنع أثاثك الخاص بنوع الخشب والتصميم الذي تريده</h3>",
  "        <p class=\"text-gray-400 mt-3 text-sm\">أرسل لنا مقاسات وتفاصيل الأثاث المطلوب تصنيعه وسيقوم مهندسونا بالتواصل معك لتقديم عرض سعر تفصيلي.</p>",
  "      </div>",
  "      <form id=\"custom-order-form\" onsubmit=\"submitCustomOrder(event)\" class=\"bg-black/40 p-8 rounded-lg border border-white/5 space-y-6\">",
  "        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\">",
  "          <div>",
  "            <label class=\"block text-sm font-medium mb-2 text-gray-300\">الاسم الكريم</label>",
  "            <input type=\"text\" id=\"customerName\" required class=\"w-full bg-[#1A1A1A] border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-sm font-medium mb-2 text-gray-300\">رقم الهاتف للتواصل</label>",
  "            <input type=\"tel\" id=\"customerPhone\" required class=\"w-full bg-[#1A1A1A] border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\">",
  "          <div>",
  "            <label class=\"block text-sm font-medium mb-2 text-gray-300\">نوع الأثاث المطلوب (مثال: ركنة مودرن)</label>",
  "            <input type=\"text\" id=\"customTitle\" required class=\"w-full bg-[#1A1A1A] border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "          <div>",
  "            <label class=\"block text-sm font-medium mb-2 text-gray-300\">نوع الخشب المفضل (مثال: زان أحمر روماني)</label>",
  "            <input type=\"text\" id=\"customWood\" required class=\"w-full bg-[#1A1A1A] border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold\">",
  "          </div>",
  "        </div>",
  "        <div>",
  "          <label class=\"block text-sm font-medium mb-2 text-gray-300\">التفاصيل، المقاسات والألوان المطلوبة</label>",
  "          <textarea id=\"customDetails\" rows=\"4\" required class=\"w-full bg-[#1A1A1A] border border-white/10 rounded px-4 py-3 text-white focus:outline-none focus:border-luxuryGold\"></textarea>",
  "        </div>",
  "        <div class=\"text-center\">",
  "          <button type=\"submit\" class=\"bg-luxuryGold text-black px-12 py-3 rounded font-bold hover:bg-yellow-500 transition-all duration-300\">إرسال طلب التصنيع</button>",
  "        </div>",
  "      </form>",
  "    </div>",
  "  </section>",
  "",
  "  <!-- الفروع وجهات الاتصال (محدثة بالأرقام الجديدة) -->",
  "  <footer class=\"bg-black text-gray-400 py-16 px-4 border-t border-luxuryGold/10\" id=\"contact\">",
  "    <div class=\"container mx-auto grid grid-cols-1 md:grid-cols-3 gap-12 text-center md:text-right\">",
  "      <div>",
  "        <h4 class=\"text-white font-bold text-lg mb-4 border-r-4 border-luxuryGold pr-3\">معرض النجار للأثاث الراقي</h4>",
  "        <p class=\"text-sm leading-relaxed\">خبرة ممتدة في صناعة أفخم أنواع الموديلات الكلاسيكية والحديثة بأرقى الأخشاب والتشطيبات الفاخرة.</p>",
  "      </div>",
  "      <div>",
  "        <h4 class=\"text-white font-bold text-lg mb-4 border-r-4 border-luxuryGold pr-3\">العنوان والفروع</h4>",
  "        <p class=\"text-sm leading-relaxed mb-2\">📍 الفرع الرئيسي: قنا - الخطارة - بجوار معرض الكويتي</p>",
  "        <p class=\"text-sm leading-relaxed\">🚚 ميزة النقل: توصيل مجاني وآمن لكافة مراكز محافظة قنا والمحافظات المجاورة.</p>",
  "      </div>",
  "      <div>",
  "        <h4 class=\"text-white font-bold text-lg mb-4 border-r-4 border-luxuryGold pr-3\">أرقام تواصل المعرض</h4>",
  "        <p class=\"text-sm leading-relaxed text-luxuryGold text-lg font-bold mb-2\">📞 01060344580</p>",
  "        <p class=\"text-sm leading-relaxed text-luxuryGold text-lg font-bold\">📞 01003989727</p>",
  "      </div>",
  "    </div>",
  "    <div class=\"text-center text-xs text-gray-600 mt-12 pt-8 border-t border-white/5 flex flex-col sm:flex-row justify-between items-center gap-4\">",
  "      <div>جميع الحقوق محفوظة © معرض النجار للأثاث الراقي</div>",
  "      <div class=\"text-gray-400 text-xs\">تصميم وتطوير المبرمج: <span class=\"text-luxuryGold font-bold\">Abdallah Abdelkader</span></div>",
  "    </div>",
  "  </footer>",
  "",
  "  <script>",
  "    // جلب المنتجات وعرضها باستخدام الدمج المباشر الآمن",
  "    async function loadProducts(category = '') {",
  "      try {",
  "        var url = '/api/products';",
  "        if (category) {",
  "          url += '?category=' + encodeURIComponent(category);",
  "        }",
  "        var response = await fetch(url);",
  "        var json = await response.json();",
  "        ",
  "        var productsGrid = document.getElementById('products-grid');",
  "        productsGrid.innerHTML = '';",
  "        ",
  "        if (!json.success || json.data.length === 0) {",
  "          productsGrid.innerHTML = '<p class=\"text-center col-span-3 text-gray-500 py-8\">لا يوجد قطع معروضة حالياً في هذا القسم.</p>';",
  "          return;",
  "        }",
  "        ",
  "        json.data.forEach(function(prod) {",
  "          var hasDiscount = prod.discountPrice && prod.discountPrice > 0;",
  "          var currentPrice = hasDiscount ? prod.discountPrice : prod.price;",
  "          ",
  "          // استخدام التشفير السحابي المباشر لعرض الصور محلياً وسحابياً",
  "          var imgUrl = prod.images[0];",
  "          ",
  "          var productHTML = '<div class=\"bg-white rounded-lg overflow-hidden shadow-md border border-gray-100 hover:shadow-xl transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl flex flex-col justify-between\">';",
  "          productHTML += '  <img src=\"' + imgUrl + '\" alt=\"' + prod.title + '\" class=\"w-full h-64 object-cover\">';",
  "          productHTML += '  <div class=\"p-6 space-y-4\">';",
  "          productHTML += '    <div class=\"flex justify-between items-start gap-2\">';",
  "          productHTML += '      <h4 class=\"font-bold text-lg text-luxuryDark\">' + prod.title + '</h4>';",
  "          productHTML += '      <span class=\"bg-luxuryGold/10 text-luxuryGold text-xs font-semibold px-2.5 py-1 rounded border border-luxuryGold/20\">' + prod.category + '</span>';",
  "          productHTML += '    </div>';",
  "          productHTML += '    <p class=\"text-gray-500 text-xs line-clamp-2 leading-relaxed\">' + prod.description + '</p>';",
  "          productHTML += '    <div class=\"text-xs text-gray-400 space-y-1\">';",
  "          productHTML += '      <div><strong>نوع الخشب:</strong> ' + prod.woodType + '</div>';",
  "          if (prod.dimensions) {",
  "            productHTML += '      <div><strong>المقاسات:</strong> ' + prod.dimensions + '</div>';",
  "          }",
  "          productHTML += '    </div>';",
  "          productHTML += '    <div class=\"flex justify-between items-center pt-2 border-t border-gray-100\">';",
  "          productHTML += '      <div class=\"flex items-baseline gap-2\">';",
  "          productHTML += '        <span class=\"text-luxuryGold font-extrabold text-xl\">' + currentPrice + ' ج.م</span>';",
  "          if (hasDiscount) {",
  "            productHTML += '        <span class=\"text-gray-400 line-through text-sm\">' + prod.price + ' ج.م</span>';",
  "          }",
  "          productHTML += '      </div>';",
  "          productHTML += '    </div>';",
  "          productHTML += '  </div>';",
  "          productHTML += '</div>';",
  "          ",
  "          productsGrid.insertAdjacentHTML('beforeend', productHTML);",
  "        });",
  "      } catch (err) {",
  "        console.error(\"فشل جلب المنتجات: \", err);",
  "      }",
  "    }",
  "",
  "    // كاشف ومعالج الصور السحابي المتكامل بتحويله لـ Base64 ليعمل على Vercel و Atlas تلقائياً",
  "    async function handleLocalUpload(event) {",
  "      const file = event.target.files[0];",
  "      if (!file) return;",
  "      ",
  "      if (file.size > 2000000) { ",
  "        alert('حجم الصورة كبير جداً، يرجى اختيار صورة أقل من 2 ميجا بايت لسرعة التصفح السحابي.');",
  "        return;",
  "      }",
  "      ",
  "      const reader = new FileReader();",
  "      reader.onloadend = function() {",
  "        const base64String = reader.result;",
  "        document.getElementById('prodImage').value = base64String;",
  "        alert('ممتاز! تم تشفير الصورة السحابية بنجاح وهي جاهزة للحفظ المباشر في المعرض!');",
  "      };",
  "      reader.readAsDataURL(file);",
  "    }",
  "",
  "    // إرسال طلب تصنيع عمولة من العميل من الواجهة",
  "    async function submitCustomOrder(event) {",
  "      event.preventDefault();",
  "      ",
  "      const payload = {",
  "        customerName: document.getElementById('customerName').value,",
  "        customerPhone: document.getElementById('customerPhone').value,",
  "        title: document.getElementById('customTitle').value,",
  "        woodTypeRequested: document.getElementById('customWood').value,",
  "        details: document.getElementById('customDetails').value",
  "      };",
  "      ",
  "      try {",
  "        const response = await fetch('/api/products/custom-order', {",
  "          method: 'POST',",
  "          headers: { 'Content-Type': 'application/json' },",
  "          body: JSON.stringify(payload)",
  "        });",
  "        ",
  "        const resJson = await response.json();",
  "        if (resJson.success) {",
  "          alert('نشكرك على ثقتك بمعرض النجار! تم استلام طلب التصنيع الخاص بك بنجاح، وسيقوم مسؤول المبيعات بالتواصل معك هاتفياً قريباً جداً.');",
  "          document.getElementById('custom-order-form').reset();",
  "        } else {",
  "          alert('حدث خطأ أثناء إرسال طلبك: ' + resJson.message);",
  "        }",
  "      } catch (err) {",
  "        alert('تعذر الاتصال بالسيرفر، يرجى التأكد من تشغيله.');",
  "      }",
  "    }",
  "",
  "    // وظائف لوحة التحكم والمدير (Admin Dashboard)",
  "    function openAdminLogin() {",
  "      document.getElementById('admin-login-modal').classList.remove('hidden');",
  "    }",
  "    function closeAdminLogin() {",
  "      document.getElementById('admin-login-modal').classList.add('hidden');",
  "      document.getElementById('adminEmailInput').value = '';",
  "      document.getElementById('adminPasswordInput').value = '';",
  "    }",
  "",
  "    // التحقق من اسم المستخدم وكلمة المرور من قاعدة البيانات (تم تعديل كاشف الخطأ التفصيلي السريع هنا)",
  "    async function verifyAdmin() {",
  "      const email = document.getElementById('adminEmailInput').value;",
  "      const password = document.getElementById('adminPasswordInput').value;",
  "      ",
  "      try {",
  "        const response = await fetch('/api/users/login', {",
  "          method: 'POST',",
  "          headers: { 'Content-Type': 'application/json' },",
  "          body: JSON.stringify({ email, password })",
  "        });",
  "        const json = await response.json();",
  "        ",
  "        if (json.success) {",
  "          alert('مرحباً بك مجدداً في نظام معرض النجار!');",
  "          document.getElementById('logged-admin-name').innerText = json.user.name + ' (' + (json.user.role === 'admin' ? 'مدير عام' : 'موظف مبيعات') + ')';",
  "          closeAdminLogin();",
  "          document.getElementById('admin-panel').classList.remove('hidden');",
  "          document.getElementById('admin-panel').scrollIntoView({ behavior: 'smooth' });",
  "          ",
  "          // كاشف وتحديد الصلاحيات الحصري للـ Admin والـ Employee",
  "          if (json.user.role === 'admin') {",
  "            document.getElementById('btn-tab-users').classList.remove('hidden'); // إظهار إدارة الحسابات للآدمن فقط",
  "          } else {",
  "            document.getElementById('btn-tab-users').classList.add('hidden'); // إخفاء إدارة الحسابات للموظف العادي",
  "          }",
  "          ",
  "          loadCustomOrders();",
  "          loadAdminProducts(); // تحميل جدول المنتجات للحذف",
  "          loadAdminUsers(); // تحميل جدول الحسابات للحذف للآدمن",
  "        } else {",
  "          alert('خطأ: ' + (json.message || json.error || 'خطأ غير معروف في الاتصال.'));",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ أثناء محاولة تسجيل الدخول لمجتمع المعرض.');",
  "      }",
  "    }",
  "",
  "    function logoutAdmin() {",
  "      document.getElementById('admin-panel').classList.add('hidden');",
  "      alert('تم تسجيل الخروج وإغلاق لوحة التحكم.');",
  "    }",
  "",
  "    // وظائف تصفح التبويبات الداخلية في الإدارة",
  "    function switchAdminTab(tabId) {",
  "      document.getElementById('tab-product').classList.add('hidden');",
  "      document.getElementById('tab-orders').classList.add('hidden');",
  "      document.getElementById('tab-fb-writer').classList.add('hidden');",
  "      document.getElementById('tab-users').classList.add('hidden');",
  "      ",
  "      document.getElementById('btn-tab-product').className = 'text-gray-400 px-4 py-1 hover:text-white';",
  "      document.getElementById('btn-tab-orders').className = 'text-gray-400 px-4 py-1 hover:text-white';",
  "      document.getElementById('btn-tab-fb-writer').className = 'text-gray-400 px-4 py-1 hover:text-white';",
  "      document.getElementById('btn-tab-users').className = 'text-gray-400 px-4 py-1 hover:text-white';",
  "      ",
  "      document.getElementById(tabId).classList.remove('hidden');",
  "      document.getElementById('btn-' + tabId).className = 'text-luxuryGold font-bold px-4 py-1 border-b-2 border-luxuryGold';",
  "    }",
  "",
  "    // إضافة منتج جديد من واجهة المدير",
  "    async function addNewProduct(event) {",
  "      event.preventDefault();",
  "      ",
  "      const payload = {",
  "        title: document.getElementById('prodTitle').value,",
  "        category: document.getElementById('prodCategory').value,",
  "        price: Number(document.getElementById('prodPrice').value),",
  "        discountPrice: Number(document.getElementById('prodDiscount').value),",
  "        woodType: document.getElementById('prodWood').value,",
  "        dimensions: document.getElementById('prodDimensions').value,",
  "        images: [document.getElementById('prodImage').value],",
  "        description: document.getElementById('prodDescription').value",
  "      };",
  "      ",
  "      try {",
  "        const response = await fetch('/api/products', {",
  "          method: 'POST',",
  "          headers: { 'Content-Type': 'application/json' },",
  "          body: JSON.stringify(payload)",
  "        });",
  "        ",
  "        const resJson = await response.json();",
  "        if (resJson.success) {",
  "          alert('ممتاز! تم حفظ ونشر القطعة الجديدة بنجاح وتحديث واجهة المعرض.');",
  "          document.getElementById('add-product-form').reset();",
  "          loadProducts(''); ",
  "          loadAdminProducts(); // تحديث قائمة الحذف الفورية",
  "        } else {",
  "          alert('فشل حفظ المنتج: ' + (resJson.message || resJson.error));",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ في الاتصال بالخادم أثناء حفظ المنتج.');",
  "      }",
  "    }",
  "",
  "    // جلب المنتجات للإدارة بغرض الحذف والإلغاء المباشر",
  "    async function loadAdminProducts() {",
  "      try {",
  "        const response = await fetch('/api/products');",
  "        const json = await response.json();",
  "        const tbody = document.getElementById('manage-products-tbody');",
  "        tbody.innerHTML = '';",
  "        ",
  "        if (!json.success || json.data.length === 0) {",
  "          tbody.innerHTML = '<tr><td colspan=\"4\" class=\"text-center p-3 text-gray-500\">لا توجد منتجات بالمعرض حالياً.</td></tr>';",
  "          return;",
  "        }",
  "        ",
  "        json.data.forEach(prod => {",
  "          const tr = document.createElement('tr');",
  "          tr.className = 'border-b border-white/5 hover:bg-white/5 text-right';",
  "          tr.innerHTML = \`",
  "            <td class=\"p-2.5 font-bold\">\${prod.title}</td>",
  "            <td class=\"p-2.5 text-luxuryGold\">\${prod.category}</td>",
  "            <td class=\"p-2.5\">\${prod.price} ج.م</td>",
  "            <td class=\"p-2.5\">",
  "              <button onclick=\"deleteProduct('\${prod._id}')\" class=\"bg-red-600/20 text-red-500 border border-red-600/40 px-3 py-1 rounded text-xs hover:bg-red-600 hover:text-white transition\">حذف القطعة</button>",
  "            </td>",
  "          \`;",
  "          tbody.appendChild(tr);",
  "        });",
  "      } catch (err) {",
  "        console.error('فشل جلب قائمة المنتجات الحذف الإداري:', err);",
  "      }",
  "    }",
  "",
  "    // حذف منتج من المعرض سحابياً",
  "    async function deleteProduct(id) {",
  "      if (!confirm('هل أنت متأكد تماماً من حذف وإزالة هذه القطعة نهائياً من المعرض؟')) return;",
  "      try {",
  "        const response = await fetch('/api/products/' + id, { method: 'DELETE' });",
  "        const json = await response.json();",
  "        if (json.success) {",
  "          alert('تم إزالة القطعة بنجاح من المعرض وتحديث الصفحة.');",
  "          loadProducts('');",
  "          loadAdminProducts();",
  "        } else {",
  "          alert('فشل الحذف: ' + json.message);",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ في الاتصال بالسيرفر أثناء الحذف.');",
  "      }",
  "    }",
  "",
  "    // جلب الموظفين والحسابات للإدارة (Admin Only)",
  "    async function loadAdminUsers() {",
  "      try {",
  "        const response = await fetch('/api/users');",
  "        const json = await response.json();",
  "        const tbody = document.getElementById('manage-users-tbody');",
  "        tbody.innerHTML = '';",
  "        ",
  "        if (!json.success || json.data.length === 0) {",
  "          tbody.innerHTML = '<tr><td colspan=\"4\" class=\"text-center p-3 text-gray-500\">لا توجد حسابات مسجلة بعد.</td></tr>';",
  "          return;",
  "        }",
  "        ",
  "        json.data.forEach(user => {",
  "          const isMainAdmin = user.email === 'admin@najjar.com';",
  "          const tr = document.createElement('tr');",
  "          tr.className = 'border-b border-white/5 hover:bg-white/5 text-right';",
  "          tr.innerHTML = \`",
  "            <td class=\"p-2.5 font-bold\">\${user.name}</td>",
  "            <td class=\"p-2.5 text-gray-400\">\${user.email}</td>",
  "            <td class=\"p-2.5 text-luxuryGold font-semibold\">\${user.role === 'admin' ? 'مدير عام' : 'موظف مبيعات'}</td>",
  "            <td class=\"p-2.5\">",
  "              \${isMainAdmin ? '<span class=\"text-gray-600 text-xs\">حساب النظام المحمي</span>' : \`<button onclick=\"deleteUser('\${user._id}')\" class=\"bg-red-600/20 text-red-500 border border-red-600/40 px-3 py-1 rounded text-xs hover:bg-red-600 hover:text-white transition\">إلغاء الصلاحية</button>\`}",
  "            </td>",
  "          \`;",
  "          tbody.appendChild(tr);",
  "        });",
  "      } catch (err) {",
  "        console.error('فشل جلب قائمة المستخدمين:', err);",
  "      }",
  "    }",
  "",
  "    // حذف وإلغاء حساب موظف سحابياً",
  "    async function deleteUser(id) {",
  "      if (!confirm('هل أنت متأكد تماماً من سحب الصلاحيات وإلغاء حساب هذا الموظف نهائياً من نظام المعرض؟')) return;",
  "      try {",
  "        const response = await fetch('/api/users/' + id, { method: 'DELETE' });",
  "        const json = await response.json();",
  "        if (json.success) {",
  "          alert('تم إلغاء تفعيل حساب الموظف وحذفه بنجاح من قاعدة البيانات.');",
  "          loadAdminUsers();",
  "        } else {",
  "          alert('فشل الحذف: ' + json.message);",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ في الاتصال بالخادم أثناء إلغاء الحساب.');",
  "      }",
  "    }",
  "",
  "    // جلب طلبات العمولة والتصنيع الخاص في لوحة الإدارة",
  "    async function loadCustomOrders() {",
  "      try {",
  "        const response = await fetch('/api/custom-orders');",
  "        const json = await response.json();",
  "        const tbody = document.getElementById('orders-table-body');",
  "        tbody.innerHTML = '';",
  "        ",
  "        if (!json.success || json.data.length === 0) {",
  "          tbody.innerHTML = '<tr><td colspan=\"9\" class=\"text-center p-4 text-gray-500\">لا توجد طلبات عمولة مسجلة بعد.</td></tr>';",
  "          return;",
  "        }",
  "        ",
  "        json.data.forEach(order => {",
  "          const remaining = order.sellingPrice - order.amountPaid;",
  "          const tr = document.createElement('tr');",
  "          tr.className = 'border-b border-white/5 hover:bg-white/5 text-right';",
  "          ",
  "          tr.innerHTML = \`",
  "            <td class=\"p-3\"><strong>\${order.customerName}</strong><br><span class=\"text-xs text-gray-500\">\${order.customerPhone}</span></td>",
  "            <td class=\"p-3\"><strong>\${order.title}</strong><br><span class=\"text-xs text-gray-400\">\${order.details}</span></td>",
  "            <td class=\"p-3 text-red-400\">\${order.costPrice} ج.م</td>",
  "            <td class=\"p-3 text-green-400 font-bold\">\${order.sellingPrice} ج.م</td>",
  "            <td class=\"p-3 text-blue-400\">\${order.amountPaid} ج.م</td>",
  "            <td class=\"p-3 text-yellow-500 font-bold\">\${remaining} ج.م</td>",
  "            <td class=\"p-3 text-gray-300\">\${order.deliveryDate || 'غير محدد'}</td>",
  "            <td class=\"p-3\">",
  "              <div class=\"w-full bg-gray-700 rounded-full h-2\">",
  "                <div class=\"bg-luxuryGold h-2 rounded-full\" style=\"width: \${order.completionPercentage}%\"></div>",
  "              </div>",
  "              <span class=\"text-xs text-luxuryGold font-bold\">\${order.completionPercentage}%</span>",
  "            </td>",
  "            <td class=\"p-3\">",
  "              <button onclick=\"openOrderUpdateModal('\${order._id}', \${order.costPrice}, \${order.sellingPrice}, \${order.amountPaid}, '\${order.deliveryDate}', \${order.completionPercentage})\" class=\"bg-luxuryGold text-black px-3 py-1 rounded text-xs font-bold hover:bg-yellow-500 transition-all duration-300\">إدارة الحساب</button>",
  "            </td>",
  "          \`;",
  "          tbody.appendChild(tr);",
  "        });",
  "      } catch (err) {",
  "        console.error('فشل جلب طلبات العمولة:', err);",
  "      }",
  "    }",
  "",
  "    // نافذة تحديث الطلبات مالياً وزمنياً",
  "    function openOrderUpdateModal(id, cost, selling, paid, date, completion) {",
  "      document.getElementById('updateOrderId').value = id;",
  "      document.getElementById('updateCost').value = cost;",
  "      document.getElementById('updateSelling').value = selling;",
  "      document.getElementById('updatePaid').value = paid;",
  "      document.getElementById('updateDelivery').value = date;",
  "      document.getElementById('updateCompletion').value = completion;",
  "      document.getElementById('order-update-modal').classList.remove('hidden');",
  "    }",
  "    function closeOrderUpdateModal() {",
  "      document.getElementById('order-update-modal').classList.add('hidden');",
  "    }",
  "    async function saveOrderUpdate() {",
  "      const id = document.getElementById('updateOrderId').value;",
  "      const payload = {",
  "        costPrice: Number(document.getElementById('updateCost').value),",
  "        sellingPrice: Number(document.getElementById('updateSelling').value),",
  "        amountPaid: Number(document.getElementById('updatePaid').value),",
  "        deliveryDate: document.getElementById('updateDelivery').value,",
  "        completionPercentage: Number(document.getElementById('updateCompletion').value)",
  "      };",
  "      ",
  "      try {",
  "        const response = await fetch('/api/custom-orders/' + id, {",
  "          method: 'PUT',",
  "          headers: { 'Content-Type': 'application/json' },",
  "          body: JSON.stringify(payload)",
  "        });",
  "        const json = await response.json();",
  "        if (json.success) {",
  "          alert('تم تحديث بيانات المقايسة المالية ونسبة الإنجاز بنجاح!');",
  "          closeOrderUpdateModal();",
  "          loadCustomOrders(); ",
  "        } else {",
  "          alert('فشل التحديث: ' + (json.message || json.error));",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ أثناء تعديل بيانات المقايسة.');",
  "      }",
  "    }",
  "",
  "    // حذف طلب العمولة نهائياً",
  "    async function deleteOrder() {",
  "      const id = document.getElementById('updateOrderId').value;",
  "      if (!confirm('هل أنت متأكد تماماً من حذف وإلغاء طلب العمولة هذا نهائياً من النظام؟ لا يمكن التراجع عن هذا الإجراء.')) return;",
  "      ",
  "      try {",
  "        const response = await fetch('/api/custom-orders/' + id, {",
  "          method: 'DELETE'",
  "        });",
  "        const json = await response.json();",
  "        if (json.success) {",
  "          alert('تم حذف وإلغاء طلب العمولة بنجاح من قاعدة البيانات.');",
  "          closeOrderUpdateModal();",
  "          loadCustomOrders();",
  "        } else {",
  "          alert('فشل حذف الطلب: ' + (json.message || json.error));",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ أثناء معالجة الحذف.');",
  "      }",
  "    }",
  "",
  "    // إضافة موظف أو مسؤول حسابات جديد",
  "    async function addNewUser(event) {",
  "      event.preventDefault();",
  "      const payload = {",
  "        name: document.getElementById('userFullName').value,",
  "        email: document.getElementById('userEmail').value,",
  "        password: document.getElementById('userPass').value,",
  "        phone: document.getElementById('userPhone').value,",
  "        role: document.getElementById('userRole').value",
  "      };",
  "      ",
  "      try {",
  "        const response = await fetch('/api/users', {",
  "          method: 'POST',",
  "          headers: { 'Content-Type': 'application/json' },",
  "          body: JSON.stringify(payload)",
  "        });",
  "        const json = await response.json();",
  "        if (json.success) {",
  "          alert('تم تسجيل الموظف الجديد بنجاح وتفعيل حسابه المالي والإداري!');",
  "          document.getElementById('add-user-form').reset();",
  "          loadAdminUsers(); // تحديث جدول الحسابات فوراً",
  "        } else {",
  "          alert('فشل تسجيل الحساب: ' + (json.message || json.error));",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ في الشبكة أثناء تسجيل الحساب الجديد.');",
  "      }",
  "    }",
  "",
  "    // وظيفة تصدير الداتا إلى شيت إكسيل (CSV مرمز للعربية UTF-8 BOM)",
  "    async function exportToExcel() {",
  "      try {",
  "        const response = await fetch('/api/custom-orders');",
  "        const json = await response.json();",
  "        ",
  "        if (!json.success || json.data.length === 0) {",
  "          alert('لا توجد طلبات عمولة لتصديرها حالياً.');",
  "          return;",
  "        }",
  "        ",
  "        let csvContent = '\\ufeff';",
  "        csvContent += 'اسم العميل,رقم الهاتف,نوع الأثاث المطلوبة,التفاصيل والمقاسات,نوع الخشب,سعر التكلفة (جملة),سعر البيع النهائي,المبلغ المدفوع,المبلغ المتبقي,تاريخ التسليم,نسبة الإنجاز,حالة الطلب\\n';",
  "        ",
  "        json.data.forEach(function(order) {",
  "          const remaining = order.sellingPrice - order.amountPaid;",
  "          const row = [",
  "            '\"' + order.customerName + '\"',",
  "            '\"' + order.customerPhone + '\"',",
  "            '\"' + order.title + '\"',",
  "            '\"' + order.details.replace(/\\\\r?\\\\n|\\\\r/g, ' ') + '\"',",
  "            '\"' + order.woodTypeRequested + '\"',",
  "            order.costPrice,",
  "            order.sellingPrice,",
  "            order.amountPaid,",
  "            remaining,",
  "            '\"' + (order.deliveryDate || 'غير محدد') + '\"',",
  "            '\"' + order.completionPercentage + '%\"',",
  "            '\"' + order.status + '\"'",
  "          ].join(',');",
  "          csvContent += row + '\\n';",
  "        });",
  "        ",
  "        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });",
  "        const url = URL.createObjectURL(blob);",
  "        const link = document.createElement('a');",
  "        link.setAttribute('href', url);",
  "        link.setAttribute('download', 'تقرير_شغل_العمولة_معرض_النجار_' + new Date().toISOString().slice(0, 10) + '.csv');",
  "        document.body.appendChild(link);",
  "        link.click();",
  "        document.body.removeChild(link);",
  "      } catch (err) {",
  "        alert('حدث خطأ أثناء تصدير شيت الإكسيل: ' + err.message);",
  "      }",
  "    }",
  "",
  "    // فتح وإغلاق نافذة إضافة طلب عمولة يدوي",
  "    function openManualOrderModal() {",
  "      document.getElementById('manual-order-modal').classList.remove('hidden');",
  "    }",
  "    function closeManualOrderModal() {",
  "      document.getElementById('manual-order-modal').classList.add('hidden');",
  "      document.getElementById('manual-order-form').reset();",
  "    }",
  "    async function submitManualOrder(event) {",
  "      event.preventDefault();",
  "      ",
  "      const payload = {",
  "        customerName: document.getElementById('mCustName').value,",
  "        customerPhone: document.getElementById('mCustPhone').value,",
  "        title: document.getElementById('mTitle').value,",
  "        woodTypeRequested: document.getElementById('mWood').value,",
  "        deliveryDate: document.getElementById('mDelivery').value,",
  "        details: document.getElementById('mDetails').value,",
  "        costPrice: Number(document.getElementById('mCostPrice').value),",
  "        sellingPrice: Number(document.getElementById('mSellingPrice').value),",
  "        amountPaid: Number(document.getElementById('mAmountPaid').value)",
  "      };",
  "      ",
  "      try {",
  "        const response = await fetch('/api/products/custom-order', {",
  "          method: 'POST',",
  "          headers: { 'Content-Type': 'application/json' },",
  "          body: JSON.stringify(payload)",
  "        });",
  "        ",
  "        const resJson = await response.json();",
  "        if (resJson.success) {",
  "          alert('تم إضافة طلب العمولة اليدوي بنجاح وإدراجه في قائمة حسابات الورشة!');",
  "          closeManualOrderModal();",
  "          loadCustomOrders(); ",
  "        } else {",
  "          alert('فشل إضافة الطلب: ' + (resJson.message || resJson.error));",
  "        }",
  "      } catch (err) {",
  "        alert('حدث خطأ في الاتصال بالخادم أثناء تسجيل الطلب اليدوي.');",
  "      }",
  "    }",
  "",
  "    // وظيفة مولّد بوستات فيسبوك التسويقية التلقائية بنقرة واحدة",
  "    function generateFacebookPost() {",
  "      const name = document.getElementById('fbProdName').value.trim();",
  "      const offer = document.getElementById('fbPromoType').value;",
  "      ",
  "      if (!name) {",
  "        alert('يرجى كتابة اسم المنتج لتوليد المنشور التسويقي بنجاح.');",
  "        return;",
  "      }",
  "      ",
  "      let postText = \"✨ عشاق الذوق الرفيع والفخامة في قنا ومصر! ✨\\n\\n\";",
  "      postText += \"يسر 👑 معرض النجار للأثاث الراقي 👑 أن يقدم لكم التحفة الفنية الجديدة: \" + name + \"! 😍\\n\\n\";",
  "      postText += \"تصميم مجسم يعكس الأناقة والراحة، ومصنع بأيدي أمهر الخبراء والمهندسين لدينا لتدوم معكم مدى الحياة! 🪵💎\\n\\n\";",
  "      postText += \"🎁 العرض الحصري الحالي: \" + offer + \"!\\n\\n\";",
  "      postText += \"📐 نقبل التصنيع المخصص والعمولة بكافة المقاسات والألوان حسب رغبتك الشخصية لضمان راحة بيتك الفريدة!\\n\\n\";",
  "      postText += \"📍 تفضلوا بزيارتنا في صالة العرض: قنا - الخطارة - بجوار معرض الكويتي.\\n\\n\";",
  "      postText += \"📞 للتواصل الهاتفي السريع والحجز:\\n\";",
  "      postText += \"- 01060344580\\n\";",
  "      postText += \"- 01003989727\\n\\n\";",
  "      postText += \"📲 أو راسلنا مباشرة عبر الواتساب بنقرة واحدة: https://wa.me/201060344580\\n\\n\";",
  "      postText += \"#معرض_النجار_للأثاث_الراقي #أثاث_راقي #قنا #تصنيع_عمولة\";",
  "      ",
  "      document.getElementById('fbPostOutput').value = postText;",
  "      document.getElementById('generated-post-container').classList.remove('hidden');",
  "      document.getElementById('fbPostOutput').scrollIntoView({ behavior: 'smooth' });",
  "    }",
  "",
  "    // نسخ نص منشور الفيسبوك بضغطة زر",
  "    function copyFbPost() {",
  "      const textarea = document.getElementById('fbPostOutput');",
  "      textarea.select();",
  "      document.execCommand('copy');",
  "      alert('تم نسخ المنشور التسويقي بنجاح! يمكنك الآن لصقه مباشرة في صفحة الفيسبوك الخاصة بالمعرض.');",
  "    }",
  "",
  "    window.onload = () => loadProducts('');",
  "  </script>",
  "</body>",
  "</html>"
].join('\n');

// ملف الخادم الرئيسي المحدث server.js مع تفعيل مسار جلب وحذف المستخدمين والمنتجات للإدارة
files['server.js'] = [
  "const express = require('express');",
  "const dotenv = require('dotenv');",
  "const multer = require('multer');",
  "const path = require('path');",
  "const fs = require('fs');",
  "const connectDB = require('./config/db');",
  "const productRoutes = require('./routes/productRoutes');",
  "const Product = require('./models/Product');",
  "const CustomOrder = require('./models/CustomOrder');",
  "const User = require('./models/User');",
  "",
  "dotenv.config();",
  "",
  "connectDB();",
  "",
  "const app = express();",
  "app.use(express.json());",
  "",
  "// تشغيل وخدمة واجهة الويب الأمامية والمرفوعات مباشرة بالمسار المطلق المتوافق مع Vercel",
  "app.use(express.static(path.join(__dirname, 'public')));",
  "",
  "// إعداد خزان رفع الصور والفيديوهات من الجهاز المحلي (Multer)",
  "const storage = multer.diskStorage({",
  "  destination: (req, file, cb) => {",
  "    cb(null, 'public/uploads/');",
  "  },",
  "  filename: (req, file, cb) => {",
  "    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);",
  "    cb(null, uniqueSuffix + path.extname(file.originalname));",
  "  }",
  "});",
  "const upload = multer({ storage: storage });",
  "",
  "// نقطة رفع الملفات المحلية من جهاز المدير",
  "app.post('/api/upload', upload.single('file'), (req, res) => {",
  "  if (!req.file) {",
  "    return res.status(400).json({ success: false, message: 'لم يتم اختيار أي ملف.' });",
  "  }",
  "  return res.json({ success: true, url: '/uploads/' + req.file.filename });",
  "});",
  "",
  "// تسجيل الدخول للمدراء والموظفين ومطابقة كلمة المرور",
  "app.post('/api/users/login', async (req, res) => {",
  "  const { email, password } = req.body;",
  "  try {",
  "    const user = await User.findOne({ email, password });",
  "    if (!user) {",
  "      return res.status(401).json({ success: false, message: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.' });",
  "    }",
  "    return res.json({",
  "      success: true,",
  "      message: 'مرحباً بك مجدداً ' + user.name,",
  "      user: { name: user.name, role: user.role }",
  "    });",
  "  } catch (error) {",
  "    return res.status(500).json({ success: false, error: error.message });",
  "  }",
  "});",
  "",
  "// جلب كافة طلبات العمولة والورشة للإدارة",
  "app.get('/api/custom-orders', async (req, res) => {",
  "  try {",
  "    const orders = await CustomOrder.find().sort({ createdAt: -1 });",
  "    return res.status(200).json({ success: true, data: orders });",
  "  } catch (error) {",
  "    return res.status(500).json({ success: false, error: error.message });",
  "  }",
  "});",
  "",
  "// تحديث تفاصيل طلب العمولة (المالية، نسبة الإنجاز والمواعيد)",
  "app.put('/api/custom-orders/:id', async (req, res) => {",
  "  try {",
  "    const updatedOrder = await CustomOrder.findByIdAndUpdate(",
  "      req.params.id,",
  "      req.body,",
  "      { new: true, runValidators: true }",
  "    );",
  "    return res.status(200).json({ success: true, data: updatedOrder });",
  "  } catch (error) {",
  "    return res.status(400).json({ success: false, message: error.message });",
  "  }",
  "});",
  "",
  "// حذف وإلغاء طلب عمولة نهائياً من الإدارة",
  "app.delete('/api/custom-orders/:id', async (req, res) => {",
  "  try {",
  "    const deletedOrder = await CustomOrder.findByIdAndDelete(req.params.id);",
  "    if (!deletedOrder) {",
  "      return res.status(404).json({ success: false, message: 'طلب العمولة غير موجود في النظام.' });",
  "    }",
  "    return res.status(200).json({ success: true, message: 'تم حذف طلب العمولة بنجاح.' });",
  "  } catch (error) {",
  "    return res.status(500).json({ success: false, error: error.message });",
  "  }",
  "});",
  "",
  "// مسار إداري خاص لحذف قطع الأثاث من المعرض سحابياً",
  "app.delete('/api/products/:id', async (req, res) => {",
  "  try {",
  "    const deletedProduct = await Product.findByIdAndDelete(req.params.id);",
  "    if (!deletedProduct) {",
  "      return res.status(404).json({ success: false, message: 'المنتج غير موجود.' });",
  "    }",
  "    return res.status(200).json({ success: true, message: 'تم إزالة المنتج بنجاح.' });",
  "  } catch (error) {",
  "    return res.status(500).json({ success: false, error: error.message });",
  "  }",
  "});",
  "",
  "// جلب كافة الموظفين والمدراء (خاص بالآدمن فقط)",
  "app.get('/api/users', async (req, res) => {",
  "  try {",
  "    const users = await User.find({}, '-password').sort({ createdAt: -1 });",
  "    return res.json({ success: true, data: users });",
  "  } catch (error) {",
  "    return res.status(500).json({ success: false, error: error.message });",
  "  }",
  "});",
  "",
  "// سحب صلاحيات وحذف حساب موظف نهائياً (خاص بالآدمن فقط - حساب المدير محمي تلقائياً)",
  "app.delete('/api/users/:id', async (req, res) => {",
  "  try {",
  "    const user = await User.findById(req.params.id);",
  "    if (user && user.email === 'admin@najjar.com') {",
  "      return res.status(400).json({ success: false, message: 'لا يمكن حذف الحساب الإداري الرئيسي للمعرض لحماية النظام.' });",
  "    }",
  "    await User.findByIdAndDelete(req.params.id);",
  "    return res.json({ success: true, message: 'تم حذف الموظف بنجاح وسحب كافة الصلاحيات.' });",
  "  } catch (error) {",
  "    return res.status(500).json({ success: false, error: error.message });",
  "  }",
  "});",
  "",
  "// إضافة حسابات موظفين ومدراء جدد في النظام",
  "app.post('/api/users', async (req, res) => {",
  "  try {",
  "    const newUser = new User(req.body);",
  "    const savedUser = await newUser.save();",
  "    return res.status(201).json({ success: true, message: 'تم تفعيل الحساب بنجاح', data: savedUser });",
  "  } catch (error) {",
  "    return res.status(400).json({ success: false, message: error.message });",
  "  }",
  "});",
  "",
  "app.use('/api/products', productRoutes);",
  "",
  "// تغذية قاعدة البيانات تلقائياً بأرقى المنتجات والمدير الرئيسي الافتراضي",
  "const seedSampleProducts = async () => {",
  "  try {",
  "    // 1. تغذية أو تحديث حساب المدير الرئيسي الافتراضي",
  "    const adminEmail = 'admin@najjar.com';",
  "    const adminUser = await User.findOne({ email: adminEmail });",
  "    if (!adminUser) {",
  "      await User.create({",
  "        name: 'المدير العام',",
  "        email: adminEmail,",
  "        password: 'admin_najjar_123',",
  "        phone: '01060344580',",
  "        role: 'admin'",
  "      });",
  "      console.log('[Auto-Seeder] تم إنشاء حساب المدير الرئيسي الافتراضي بنجاح!');",
  "    } else {",
  "      // إعادة تعيين كلمة المرور الافتراضية لضمان الدخول في حال تداخل البيانات القديمة",
  "      adminUser.password = 'admin_najjar_123';",
  "      await adminUser.save();",
  "      console.log('[Auto-Seeder] تم التحقق من حساب المدير وإعادة تعيين الباسوورد الافتراضي بنجاح!');",
  "    }",
  "",
  "    // 2. تغذية المنتجات الافتراضية",
  "    const count = await Product.countDocuments();",
  "    if (count === 0) {",
  "      const sampleData = [",
  "        {",
  "          title: 'غرفة نوم الملكة الفاخرة',",
  "          description: 'غرفة نوم كاملة مودرن بتفاصيل مذهبة وألوان متناسقة تناسب ذوقك الرفيع، مصنوعة بالكامل من الخشب الطبيعي المجفف.',",
  "          price: 45000,",
  "          discountPrice: 33750,",
  "          category: 'غرف نوم',",
  "          woodType: 'خشب زان أحمر فرنسي',",
  "          dimensions: 'سرير 180سم - دولاب 280سم',",
  "          images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=600']",
  "        },",
  "        {",
  "          title: 'غرفة نوم الأطفال ميكي السحرية',",
  "          description: 'غرفة نوم أطفال مبهجة بتصميم عصري ملون، تشمل سريرين ودولاب مدمج بتفاصيل محببة ومقاومة لحركة الأطفال.',",
  "          price: 22000,",
  "          discountPrice: 16500,",
  "          category: 'غرف أطفال',",
  "          woodType: 'خشب سويدي متين كبس',",
  "          dimensions: 'سرير 120سم - دولاب 160سم',",
  "          images: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=600']",
  "        },",
  "        {",
  "          title: 'صالون قصر النبلاء المذهب',",
  "          description: 'صالون كلاسيكي فخم مذهب بأيدي أمهر الصناع بدمياط، وحياكة فاخرة تليق بقاعات استقبال الضيوف.',",
  "          price: 38000,",
  "          discountPrice: 28500,",
  "          category: 'انتريه',",
  "          woodType: 'زان روماني مذهب',",
  "          dimensions: 'كنبة 3 مقاعد، كنبة مقعدين، و2 فوتيه مع طاولة مذهبة',",
  "          images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=600']",
  "        },",
  "        {",
  "          title: 'سفرة فرساي الملكية مع 8 كراسي',",
  "          description: 'طاولة سفرة فخمة مع 8 كراسي مبطنة بنسيج قطني فاخر، تتميز بزجاج حراري مقاوم للصدمات.',",
  "          price: 32000,",
  "          discountPrice: 24000,",
  "          category: 'سفرة',",
  "          woodType: 'زان أحمر طبيعي متين',",
  "          dimensions: 'طول 220سم - عرض 110سم',",
  "          images: ['https://images.unsplash.com/photo-1577140917170-285929fb55b7?q=80&w=600']",
  "        }",
  "      ];",
  "      await Product.insertMany(sampleData);",
  "      console.log('[Auto-Seeder] تم تعبئة المعرض بـ 4 منتجات تجريبية فاخرة بنجاح!');",
  "    }",
  "  } catch (err) {",
  "    console.error('[Seeder Error] فشل التغذية التلقائية: ' + err.message);",
  "  }",
  "};",
  "",
  "seedSampleProducts();",
  "",
  "// تشغيل الاستماع محلياً فقط وتفادي تشغيله على Vercel لمنع الـ Crash",
  "if (!process.env.VERCEL) {",
  "  const PORT = process.env.PORT || 5000;",
  "  app.listen(PORT, () => {",
  "    console.log('--------------------------------------------------');",
  "    console.log('Server is running locally on port: ' + PORT);",
  "    console.log('--------------------------------------------------');",
  "  });",
  "}",
  "",
  "// تصدير الخادم السحابي لمنصة Vercel لمنع أخطاء البناء",
  "module.exports = app;"
].join('\n');

// ملف تشغيل السيرفر start_server.cmd بضغطة زر لويندوز
files['start_server.cmd'] = [
  "@echo off",
  "title Al-Najjar Showroom Web Server",
  "echo ===========================================================",
  "echo   Al-Najjar Showroom Web Server Startup Tool (Windows)      ",
  "echo ===========================================================",
  "echo.",
  "echo 1. Installing required node packages... Please wait.",
  "call npm install",
  "echo.",
  "echo 2. Launching Backend Web Server in Development Mode...",
  "echo.",
  "call npm run dev",
  "pause"
].join('\n');

// ملف التعليمات للمستخدم العادي وغير التقني README_USER.txt (محدث بالأرقام الجديدة)
files['README_USER.txt'] = [
  "========================================================================",
  "    دليل تشغيل موقع معرض النجار للأثاث الراقي (للمستخدم العادي)",
  "========================================================================",
  "",
  "أهلاً بك! هذا الملف مخصص لمساعدتك في تشغيل موقع المعرض على جهازك خطوة بخطوة وبكل سهولة دون الحاجة لخبرة برمجية.",
  "",
  "------------------------------------------------------------------------",
  "أولاً: المتطلبات الأساسية للتشغيل (تقوم بتثبيتها مرة واحدة فقط):",
  "------------------------------------------------------------------------",
  "1. برنامج Node.js (المحرك المشغل للموقع):",
  "   - قم بتحميله وتثبيته مباشرة عبر الضغط على هذا الرابط وتثبيته بالخيارات الافتراضية:",
  "   👉 الرابط: https://nodejs.org/dist/v20.18.0/node-v20.18.0-x64.msi",
  "",
  "2. قاعدة بيانات MongoDB (الإصدار المستقر 7.0 الموصى به):",
  "   - قم بتحميله وتثبيته لكي يقوم بحفظ المنتجات وطلبات الزبائن:",
  "   👉 الرابط: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-7.0.12-signed.msi",
  "   - أثناء التثبيت، اضغط التالي (Next) في كل الخطوات حتى النهاية للتثبيت التلقائي كخدمة نظام تعمل لوحدها.",
  "",
  "------------------------------------------------------------------------",
  "ثانياً: طريقة تشغيل الموقع ودخوله بضغطة زر:",
  "------------------------------------------------------------------------",
  "1. اذهب لمجلد المشروع (al-najjar-showroom).",
  "2. اضغط مرتين متتاليتين (Double Click) على الملف المسمى: [ start_server.cmd ].",
  "3. ستظهر لك شاشة سوداء تقوم بتحميل وتثبيت الملفات اللازمة تلقائياً.",
  "4. انتظر ثوانٍ حتى ترى جملة النجاح بالإنجليزية:",
  "   [ Visit: http://localhost:5000 in your browser! ]",
  "",
  "5. الآن، افتح متصفح الإنترنت العادي بجهازك (مثل جوجل كروم أو إيدج) واكتب في الأعلى الرابط التالي ثم اضغط دخول:",
  "   👉 الرابط: http://localhost:5000",
  "",
  "6. حساب المدير الرئيسي الافتراضي للدخول للوحة الإدارة:",
  "   - البريد الإلكتروني: admin@najjar.com",
  "   - كلمة المرور: admin_najjar_123",
  "   - أرقام التواصل بالمعرض: 01060344580 - 01003989727",
  "",
  "مبروك! الموقع الآن يعمل بكامل تفاصيله وجماله الفاخر أمامك محلياً على جهازك ويقوم بحفظ الطلبات وتصفح الأقسام والقطع الراقية بنجاح تام.",
  "========================================================================"
].join('\n');

// ملف تكوين الاستثناءات السحابية .gitignore لعدم رفع الحزم الثقيلة
files['.gitignore'] = [
  "node_modules/",
  ".env",
  "public/uploads/*",
  "!public/uploads/.gitkeep"
].join('\n');


// دالة معالجة التوليد التلقائي لملفات الموقع المتكامل
function buildProject() {
  console.log('--- Rebuilding Al-Najjar Web-Only Project ---');

  directories.forEach(dir => {
    const dirPath = path.join(__dirname, dir);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      console.log('[+] Created Directory: ' + dir);
    }
  });

  Object.entries(files).forEach(([filePath, content]) => {
    const fullPath = path.join(__dirname, filePath);
    fs.writeFileSync(fullPath, content, 'utf8');
    console.log('[+] Created File: ' + filePath);
  });

  console.log('\n--- Web Project Rebuilt Successfully! ---');
  console.log('Ready to run out-of-the-box.');
}

buildProject();